/*
  store/favoritesSlice.ts

  ============================================================
  WHAT IS A SLICE?
  ============================================================

  In old Redux (what you likely used at bootcamp), you had three
  separate files for a single feature:
    1. actions.ts         — action type constants + action creators
    2. reducer.ts         — the switch/case reducer function
    3. selectors.ts       — functions to read from state

  Redux Toolkit introduces createSlice(), which combines all three
  into a single file. The "slice" is your feature's piece of the
  overall Redux store.

  This file owns everything about the favorites feature:
    - The state shape (what data we store)
    - The actions (what can happen to that data)
    - The reducer (how the data changes in response to actions)
    - The selectors (how components read the data)

  ============================================================
  WHAT IS IMMER? (READ THIS — IT WILL LOOK WRONG AT FIRST)
  ============================================================

  In old Redux, reducers had to return a NEW object every time
  because Redux requires immutability. You couldn't mutate state
  directly. This led to verbose spread syntax:

    // OLD Redux reducer:
    case ADD_FAVORITE:
      return {
        ...state,
        pokemon: [...state.pokemon, action.payload],
      };

  RTK bundles Immer (https://immerjs.github.io/immer/), which
  intercepts any mutations you make inside a reducer and produces
  a new immutable copy behind the scenes. This means you CAN write
  code that looks like a mutation:

    // RTK reducer with Immer:
    addFavorite: (state, action) => {
      state.pokemon.push(action.payload); // looks like mutation — it's safe
    }

  Both produce identical results. The Immer version just looks like
  normal JavaScript. You'll see both styles below:
    - push() for adding  (mutation style)
    - filter assignment for removing (also valid in Immer)

  ============================================================
  NOTE ON createEntityAdapter
  ============================================================

  The RTK-idiomatic pattern for a collection of entities is
  createEntityAdapter(), which normalizes the data as:
    { ids: number[], entities: Record<number, FavoritePokemon> }

  It auto-generates selectors and makes lookups O(1).
  We use a plain array here for clarity while learning. In a
  production app with hundreds of items, createEntityAdapter
  is the better choice.
  See: https://redux-toolkit.js.org/api/createEntityAdapter
*/

import {createSlice, type PayloadAction} from '@reduxjs/toolkit';
import type {FavoritePokemon} from '@/types/pokemon';

/*
  Import RootState as a TYPE ONLY to define our selectors below.

  This creates a circular dependency:
    favoritesSlice → imports RootState from store/index.ts
    store/index.ts → imports favoritesReducer from favoritesSlice

  TypeScript handles type-only circular imports correctly.
  The `import type` keyword tells TypeScript this import is erased
  at runtime — no actual JavaScript circular dependency exists.
*/
import type {RootState} from './index';

/* ============================================================
   STATE SHAPE
   ============================================================ */

interface FavoritesState {
  pokemon: FavoritePokemon[];
}

const initialState: FavoritesState = {
  pokemon: [],
  /*
    No "hydrated" flag here. Some implementations add a flag to
    track whether localStorage has been loaded into the store.
    We avoid it by reading localStorage synchronously when the
    store is created in makeStore() (store/index.ts), so the
    store starts with correct data on the very first render.
    Keeping infrastructure state out of Redux is better practice.
  */
};

/* ============================================================
   THE SLICE
   ============================================================ */

export const favoritesSlice = createSlice({
  /*
    name: a string prefix for all action types generated by this slice.
    Actions become: "favorites/addFavorite", "favorites/removeFavorite"
    You'll see these names in the Redux DevTools.
  */
  name: 'favorites',
  initialState,

  /*
    reducers: an object where each key becomes both:
      1. An action creator (exported below)
      2. A case in the reducer

    In old Redux you wrote these separately:
      const ADD_FAVORITE = "ADD_FAVORITE";
      const addFavorite = (pokemon) => ({ type: ADD_FAVORITE, payload: pokemon });
      function reducer(state, action) {
        switch (action.type) {
          case ADD_FAVORITE: return { ...state, pokemon: [...state.pokemon, action.payload] }
        }
      }

    With createSlice, you write one object and get all of that automatically.
  */
  reducers: {
    /*
      addFavorite
      -----------
      PayloadAction<FavoritePokemon> means this action carries a FavoritePokemon
      as its payload. TypeScript will enforce this at every dispatch() call site.

      NOTE: addedAt is stamped by the COMPONENT before dispatching (Date.now()),
      not here in the reducer. Reducers should be pure functions — same input
      always produces the same output. Date.now() breaks purity because it
      returns a different value on every call.

      IMMER IN ACTION:
      state.pokemon.push() looks like a direct array mutation.
      It would be wrong in plain React (never mutate state directly!).
      Inside an RTK reducer, Immer intercepts this and creates a new
      array behind the scenes — the store state is never actually mutated.
    */
    addFavorite: (state, action: PayloadAction<FavoritePokemon>) => {
      // Idempotent — silently ignore if already favorited
      const alreadyExists = state.pokemon.some((p) => p.id === action.payload.id);
      if (!alreadyExists) {
        state.pokemon.push(action.payload); // Immer handles immutability
      }
    },

    /*
      removeFavorite
      --------------
      Payload is just the Pokémon's id — we only need the ID to remove it.

      This uses direct reassignment (state.pokemon = ...) rather than
      a mutation method. This is also valid in Immer — you can either
      mutate the existing draft OR return/assign a new value.

      Compare to old Redux:
        case REMOVE_FAVORITE:
          return { ...state, pokemon: state.pokemon.filter(p => p.id !== action.payload) }
    */
    removeFavorite: (state, action: PayloadAction<number>) => {
      state.pokemon = state.pokemon.filter((p) => p.id !== action.payload);
    },
  },
});

/* ============================================================
   EXPORTS
   ============================================================ */

/*
  Export the action creators.
  These are the functions you call inside dispatch():
    dispatch(addFavorite({ id: 25, name: "pikachu", ... }))
    dispatch(removeFavorite(25))

  createSlice generates these automatically from the reducers object.
  In old Redux, you wrote these by hand.
*/
export const {addFavorite, removeFavorite} = favoritesSlice.actions;

/*
  Export the reducer — used by configureStore in store/index.ts.
  This is the function Redux calls when an action is dispatched.
*/
export default favoritesSlice.reducer;

/* ============================================================
   SELECTORS
   Co-located with the slice for discoverability. Import them
   anywhere you need to read favorites from the store.
   ============================================================ */

/*
  selectFavorites
  ---------------
  Returns the full array of favorited Pokémon.
  Use this in FavoritesGrid to render all favorites.

  In RN you'd pass this data down as props. With Redux, any
  component can call useAppSelector(selectFavorites) directly —
  no prop drilling through parent components.
*/
export const selectFavorites = (state: RootState) => state.favorites.pokemon;

/*
  selectFavoritesCount
  --------------------
  Returns the number of favorited Pokémon.
  Used in the Navbar to show the badge count.
*/
export const selectFavoritesCount = (state: RootState) => state.favorites.pokemon.length;

/*
  selectIsFavorite
  ----------------
  A "selector factory" — a function that returns a selector function.
  This is how RTK/Redux handles parameterized selectors.

  Usage: useAppSelector(selectIsFavorite(25))  ← pass the id
  Returns: true if Pokémon #25 is favorited, false otherwise.

  NOTE ON createSelector (MEMOIZATION):
  RTK bundles reselect's createSelector for memoized derived selectors.
  We don't use it here because selectIsFavorite returns a primitive
  boolean. useSelector already skips re-renders when the result hasn't
  changed (it compares the return value with ===).

  You'd reach for createSelector when:
    - The selector does an expensive computation
    - The selector returns a new object/array on every call
      (breaking === equality, causing unnecessary re-renders)

  Example where you'd need it:
    // BAD — returns a new array reference every time:
    const selectFireTypes = (state) => state.pokemon.filter(p => p.type === 'fire')

    // GOOD — memoized, only recomputes when state.pokemon changes:
    const selectFireTypes = createSelector(
      (state) => state.pokemon,
      (pokemon) => pokemon.filter(p => p.type === 'fire')
    )
*/
export const selectIsFavorite = (id: number) => (state: RootState) => state.favorites.pokemon.some((p) => p.id === id);
